environment:
  matrix:
    - nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - npm set verify-store-integrity false
  - npm set fetch-retry-maxtimeout 180000
  - set PNPM_VERSION=1.33.2
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  # Testing whether pnpm can upgrade itself
  - pnpm i -g pnpm@next
  - pnpm -v
  - pnpm recursive link --no-lock
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm t --prefix packages/config
  - npm t --prefix packages/utils
  - npm t --prefix packages/headless
  - npm t --prefix packages/supi
  - npm t --prefix packages/default-reporter
  - npm t --prefix packages/pnpm
skip_tags: true
